import { IFormValues } from "./interface";

export const initialValues: IFormValues = {
  registrationNumber: "",
  fullName: "",
  mobileNumber: "",
  whatsAppNumber: "",
  fatherName: "",
  dob: new Date(),
  qualification: "",
  email: "",
  gender: "",
  state: "",
  district: "",
  address: "",
  fatherOccupation: "",
  sportsExperience: "",
  optionToLearn: [],
  consent: "",
  blackCourse: false,
  img: "",
  starRating: "",
  title: "",
  ageCategory: "",
  category: "",
  certificateNumber: "",
  photo: "",
  club: "",
  academy: "",
  school: "",
  award: "",
  position: "",
  designation: "",
  eventVenue: "",
  eventDate: new Date(),
  certificateNo: "",
};
